image: nvidia/cuda:11.8.0-devel-ubuntu22.04

variables:
  DEBIAN_FRONTEND: noninteractive
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

before_script:
  - apt update
  - apt install -y sudo cmake make git libtool-bin autoconf automake python3

test:
  tags:
    - docker,nvidia
  stage: build
  script:
    - make 
    - make test-small
