name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run bench
      run: ./bench.sh
    - name: run bench unrolling
      run: ./bench_unrolling.sh
